// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/haberdasher/service.proto

package haberdasher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Size of a Hat, in inches.
type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8fa1944a252d3053, []int{0}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

// A Hat is a piece of headwear made by a Haberdasher.
type Hat struct {
	Inches               int32    `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	Color                string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8fa1944a252d3053, []int{1}
}
func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (dst *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(dst, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Size)(nil), "twirp.example.haberdasher.Size")
	proto.RegisterType((*Hat)(nil), "twirp.example.haberdasher.Hat")
}

func init() {
	proto.RegisterFile("rpc/haberdasher/service.proto", fileDescriptor_service_8fa1944a252d3053)
}

var fileDescriptor_service_8fa1944a252d3053 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x2a, 0x48, 0xd6,
	0xcf, 0x48, 0x4c, 0x4a, 0x2d, 0x4a, 0x49, 0x2c, 0xce, 0x48, 0x2d, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x2c, 0x29, 0xcf, 0x2c, 0x2a,
	0xd0, 0x4b, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x43, 0x52, 0xa8, 0x24, 0xc7, 0xc5, 0x12,
	0x9c, 0x59, 0x95, 0x2a, 0x24, 0xc6, 0xc5, 0x96, 0x99, 0x97, 0x9c, 0x91, 0x5a, 0x2c, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x29, 0xb9, 0x73, 0x31, 0x7b, 0x24, 0x96, 0xe0, 0x92, 0x16,
	0x12, 0xe1, 0x62, 0x4d, 0xce, 0xcf, 0xc9, 0x2f, 0x92, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0x70, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc1, 0x82, 0x60, 0xb6, 0x51,
	0x24, 0x17, 0xb7, 0x07, 0xc2, 0x5e, 0x21, 0x2f, 0x2e, 0x76, 0xdf, 0xc4, 0xec, 0x54, 0x90, 0xd9,
	0xf2, 0x7a, 0x38, 0x9d, 0xa7, 0x07, 0x72, 0x9b, 0x94, 0x1c, 0x1e, 0x05, 0x1e, 0x89, 0x25, 0x4e,
	0xbc, 0x51, 0xdc, 0x48, 0x42, 0x49, 0x6c, 0x60, 0x4f, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0x99, 0x03, 0x82, 0x15, 0x01, 0x00, 0x00,
}
